spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: Adm!n123$
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 1663

inventory:
  url: http://localhost:1664

